### ISSUE TITLE
error when running code : Need Help!!

### ISSUE THREAD

**Issue by Wmir** [wenguanwang/ASNet#8]
Thanks for sharing your code. I have tried to run your model however I am getting an error. if possible can you please help me out to resolve this error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __setattr__(self, name, value)
   2761       try:
-> 2762         super(tracking.AutoTrackable, self).__setattr__(name, value)
   2763       except AttributeError:

AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __setattr__(self, name, value)
   2765             ('Can\'t set the attribute "{}", likely because it conflicts with '
   2766              'an existing read-only @property of the object. Please choose a '
-> 2767              'different name.').format(name))
   2768       return
   2769 

AttributeError: Can't set the attribute "trainable_weights", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.

**Comment by wenguanwang** [comment]
@Wmir This is obviously caused by some version matching issues. These bugs are not related to my own code. Please search the solution on Keras or Tensorflow bbs, instead of directly asking the authors to help u solve these issues.

**Comment by zhb2000** [comment]
Modify this line
```python3
self.trainable_weights = [self.W]
```

Add an underscore

```python3
self._trainable_weights = [self.W]
```
