### ISSUE TITLE
What are learning priors ?

### ISSUE THREAD

**Issue by Pelursos** [wenguanwang/ASNet#9]
Hello,
First, thanks for this great job and for sharing it.
I don't understand what is the purpose in LearningPrior in your code. It doesn't seem to be describe in your paper.
Can you please explain this part ?
It also seems that a convLSTM is used to predit the attention map, isn't it ?

Thank you

**Comment by wenguanwang** [comment]
@Pelursos Hi, Thanks for your interest. 

Here we learn a Gaussian Prior for a more accurate fixation map estimation. This is a widely used trick in the field of eye fixation prediction. You can find more details here : ) Predicting Human Eye Fixations via an LSTM-based Saliency Attentive Model.
